source 'https://github.com/SourceChang/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'MapWrapperFramework_Example' do
  pod 'MapWrapperFramework', :path => '../'

  target 'MapWrapperFramework_Tests' do
    inherit! :search_paths

    
  end
end
